// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prc-variants/FocusMode.tsx": () => import("../components/mockups/prc-variants/FocusMode.tsx"),
  "./components/mockups/prc-variants/MatchAligned.tsx": () => import("../components/mockups/prc-variants/MatchAligned.tsx"),
  "./components/mockups/prc-variants/OperatorDeck.tsx": () => import("../components/mockups/prc-variants/OperatorDeck.tsx"),
  "./components/mockups/prc-variants/PatientUnified.tsx": () => import("../components/mockups/prc-variants/PatientUnified.tsx"),
  "./components/mockups/prc-variants/StagingZone.tsx": () => import("../components/mockups/prc-variants/StagingZone.tsx"),
  "./components/mockups/prc-variants/UrgencyTriage.tsx": () => import("../components/mockups/prc-variants/UrgencyTriage.tsx")
};
